'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
const pieces=[['Table Orme N°04','Orme massif · 240×95cm','table-orme'],['Fauteuil Noyer N°02','Noyer français · cuir naturel','fauteuil-noyer'],['Bibliothèque Chêne N°07','Chêne massif · sur mesure','bibliotheque-chene'],['Banc Frêne N°03','Frêne · assemblage traditionnel','banc-frene']];
const steps=[['La matière','Une planche de noyer, choisie pour son fil et sa couleur.'],['Le dessin','Chaque pièce commence par un plan, tracé à la main.'],['La coupe','Le bois est débité selon les cotes exactes du projet.'],["L'assemblage","Tenons, mortaises, chevilles : l'assemblage traditionnel, sans clou."],['La finition','Ponçage progressif, puis huile naturelle appliquée à la main.'],['La pièce','La table Noyer N°06, prête à rejoindre votre intérieur.']];
const woods=[['Orme','Veinage marqué, teinte miel à brun.'],['Noyer','Grain fin, couleur chocolat profonde.'],['Chêne','Robuste, teinte dorée, se patine avec le temps.'],['Frêne','Clair, souple, idéal pour les pièces fines.']];
function Arrow(){return <span aria-hidden="true">↗</span>}
export default function Home(){
const [menu,setMenu]=useState(false),[active,setActive]=useState(0),[sent,setSent]=useState(false); const rail=useRef<HTMLDivElement>(null);
useEffect(()=>{const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>obs.observe(el));return()=>obs.disconnect()},[]);
function go(i:number){const el=rail.current?.children[i] as HTMLElement;el?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest',inline:'start'});}
return <><a className="skip" href="#main">Aller au contenu</a><header className="header"><a className="brand" href="#" aria-label="Cendre et Chêne — accueil">CENDRE <span>&</span> CHÊNE<small>ATELIER D’ÉBÉNISTERIE · ANNECY</small></a><nav aria-label="Navigation principale" className={menu?'open':''}>{[['ATELIER','atelier'],['PIÈCES','pieces'],['SAVOIR-FAIRE','savoir-faire'],['CONTACT','contact']].map(([t,id])=><a onClick={()=>setMenu(false)} href={'#'+id} key={id}>{t}</a>)}</nav><a className="nav-cta" href="#contact">UN PROJET ? <Arrow/></a><Button variant="ghost" className="menu-toggle" aria-expanded={menu} aria-label={menu?'Fermer le menu':'Ouvrir le menu'} onClick={()=>setMenu(!menu)}>{menu?'FERMER −':'MENU +'}</Button></header>
<main id="main"><section className="hero"><img className="hero-img" src="/images/hero.webp" alt="Table en noyer dans la lumière de l’atelier" fetchPriority="high"/><div className="hero-shade"/><div className="hero-content"><p className="eyebrow">ÉBÉNISTERIE CONTEMPORAINE — DEPUIS 2008</p><h1>LE BOIS.<br/>LE GESTE.<br/>LE TEMPS.</h1><p className="hero-sub">Mobilier conçu et fabriqué à la main, à Annecy.</p><div className="hero-actions"><a className="cta light" href="#contact">Parler de votre projet <Arrow/></a><a className="text-link" href="#pieces">Découvrir les pièces <span aria-hidden="true">↓</span></a></div></div><div className="hero-bottom"><a href="#atelier" aria-label="Descendre vers l’atelier">FAIRE DÉFILER <span aria-hidden="true">↓</span></a></div><span className="hero-side">45°54′ N — 6°07′ E</span></section>
<section id="atelier" className="atelier section"><div className="section-index"><span>01 / L’ATELIER</span><span>ANNECY, HAUTE-SAVOIE</span></div><div className="atelier-grid reveal"><h2>Un métier qui <br/>prend son temps</h2><div><p className="atelier-text">Cendre & Chêne est né en 2008, d'une conviction simple : un meuble bien fait dure plus longtemps qu'une mode. Élias Cendre, ébéniste fondateur, a appris son métier dans plusieurs ateliers avant d'ouvrir le sien. Ici, chaque pièce est pensée avec le client, dessinée à la main, puis fabriquée à l'atelier, sans sous-traitance, sans raccourci.</p><p className="signature">Élias Cendre <span>ÉBÉNISTE FONDATEUR</span></p></div></div><div className="facts reveal">{['Depuis 2008','Pièces sur mesure','Bois français','Fabrication locale'].map((x,i)=><div key={x}><span className="fact-no">0{i+1}</span><p>{x}</p></div>)}</div></section>
<section id="pieces" className="pieces section"><div className="section-index"><span>02 / PIÈCES</span><span>UNE SÉLECTION DE L’ATELIER</span></div><div className="section-head reveal"><h2>La matière<br/>prend forme.</h2><p>Quatre pièces, quatre essences. Chacune existe en un seul exemplaire.</p></div><div className="gallery">{pieces.map(([name,desc,img],i)=><article className={'piece reveal piece-'+i} key={name}><div className="piece-image"><img src={'/images/'+img+'.webp'} alt={name+' — '+desc} loading="lazy"/><span className="image-label">PIÈCE UNIQUE / 0{i+1}</span></div><div className="piece-caption"><h3>{name}</h3><p>{desc}</p></div></article>)}</div></section>
<section id="savoir-faire" className="process section"><div className="section-index"><span>03 / DU BOIS À LA PIÈCE</span><span>TABLE NOYER N°06 · 220×100CM</span></div><div className="section-head reveal"><h2>Une pièce, <br/>six étapes</h2><p>Voici comment naît une table Cendre & Chêne, de la planche brute à la pièce livrée.</p></div><div className="step-nav" aria-label="Étapes de fabrication">{steps.map(([name],i)=><button key={name} onClick={()=>go(i)} aria-current={active===i?'step':undefined}><span>0{i+1}</span>{name}</button>)}</div><div ref={rail} className="process-rail" tabIndex={0} aria-label="Les six étapes, défilement horizontal" onScroll={()=>{const el=rail.current;if(el)setActive(Math.round(el.scrollLeft/((el.children[0] as HTMLElement).offsetWidth+24)))}}>{steps.map(([name,desc],i)=><article className="step" key={name}><div className="step-photo"><img src={'/images/step-'+(i+1)+'.webp'} alt={name+' — fabrication de la table Noyer N°06'} loading="lazy"/><span>0{i+1} / 06</span></div><div className="step-caption"><h3>{name}</h3><p>{desc}</p></div></article>)}</div><div className="rail-controls"><p>UN MÊME BOIS. UN MÊME FIL.</p><div><Button variant="ghost" aria-label="Étape précédente" disabled={active===0} onClick={()=>go(active-1)}>←</Button><span>0{active+1} / 06</span><Button variant="ghost" aria-label="Étape suivante" disabled={active===5} onClick={()=>go(active+1)}>→</Button></div></div></section>
<section id="matieres" className="materials section"><div className="section-index"><span>04 / MATIÈRES</span><span>BOIS FRANÇAIS</span></div><h2 className="reveal">Quatre essences, <br/>une provenance</h2><div className="wood-grid">{woods.map(([name,desc],i)=><article className="wood reveal" key={name}><div className={'wood-photo wood-'+i}><img src={'/images/'+pieces[i][2]+'.webp'} alt={'Détail du bois — '+name} loading="lazy"/></div><span className="wood-number">0{i+1}</span><h3>{name}</h3><p>{desc}</p></article>)}</div></section>
<section id="contact" className="contact section"><div className="section-index"><span>05 / COMMANDE</span><span>DU PREMIER ÉCHANGE À VOTRE INTÉRIEUR</span></div><h2 className="reveal">Une pièce sur mesure, <br/>en quatre étapes</h2><div className="order-steps reveal">{['Rencontre','Croquis','Fabrication','Livraison'].map((x,i)=><div key={x}><span>0{i+1}</span><h3>{x}</h3></div>)}</div><div className="contact-grid reveal"><div className="contact-intro"><p className="eyebrow">LE DÉBUT D’UNE PIÈCE</p><h3>Parlez-nous de la pièce que vous imaginez.</h3><p>Atelier Cendre & Chêne<br/>Annecy, Haute-Savoie</p></div><form onSubmit={e=>{e.preventDefault();setSent(true)}} onChange={()=>setSent(false)}><div className="form-row"><label htmlFor="name">VOTRE NOM *<Input id="name" name="name" autoComplete="name" maxLength={100} required placeholder="Prénom et nom"/></label><label htmlFor="email">VOTRE E-MAIL *<Input id="email" name="email" type="email" autoComplete="email" maxLength={200} required placeholder="vous@exemple.fr"/></label></div><label htmlFor="project">VOTRE PROJET *<Textarea id="project" name="project" required minLength={10} maxLength={5000} placeholder="Une pièce, une essence, des dimensions, une envie…"/></label><p className="form-note">Site de démonstration : ce formulaire n’envoie aucun message. Vos informations ne sont pas conservées.</p><Button type="submit" className="cta submit">Parler de votre projet <Arrow/></Button><p role="status" className="form-status">{sent?'Votre projet est prêt. Démonstration validée : aucun message n’a été envoyé.':''}</p></form></div></section></main>
<footer><div className="footer-top"><a href="#" className="footer-brand">CENDRE <span>&</span> CHÊNE</a><a href="#" className="back-top">RETOUR EN HAUT ↑</a></div><div className="footer-bottom"><p>Concept créé par Megahana — marque fictive à des fins de démonstration.</p><span>ANNECY · DEPUIS 2008</span></div></footer></>}
